### ISSUE TITLE
Difficulty getting SparkPost extension operating correctly in CiviCRM on WordPress

### ISSUE THREAD

**Issue by caniwigirl** [cividesk/com.cividesk.email.sparkpost#10]
I have followed the instructions under SETUP STEPS, but as sone as I install and enable the extension (v1.3) in my WordPress site running CiviCRM 4.6.12, it no longer sends email through CiviMail, however it still send transactional email from WordPress. 

When enabled, the scheduled job for SparkPost Action: Fetchbounces completes with a result of: Success (a:0:{})

CiviMail email send fine when the extension is NOT enabled.

Any suggestions?

Cheers

**Comment by nganivet** [comment]
You must be using another SparkPost extension, this one does not have a scheduled job and works differently. You can check by going to Administer >> System Settings >> Manage Extensions and looking for SparkPost. You will see it is not the same extension, this one is: SparkPost integration (com.cividesk.email.sparkpost).

**Comment by caniwigirl** [comment]
I have just installed and enabled v1.2 of SparkPost / CiviCRM Integration, and kept the SparkPost Fetch Bounces job scheduled with the appropriate API key and from address stipulated and it seems to be working now. I downloaded v1.3 from the link on same page, but it didn't work.

**Comment by nganivet** [comment]
Again, this is not the same extension. Please file your support questions with the other author.
