### ISSUE TITLE
Installation fails with PHP fatal error (PHP versions > 7.3)

### ISSUE THREAD

**Issue by mark-orion** [cividesk/com.cividesk.email.sparkpost#100]
The problem: PHP bails out with a blank page in the browser and with the following error in the log:
PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in....

The fix is to get rid of the curly braces in line 155 of /civicrm/ext/com.cividesk.email.sparkpost/sparkpost.civix.php
Line 155 should look like this:
if ($entry[0] == '.') {

**Comment by nganivet** [comment]
@mark-orion Thanks, fixed with the latest commit
