### ISSUE TITLE
My CiviCRM transactional emails aren't being sent

### ISSUE THREAD

**Issue by caniwigirl** [cividesk/com.cividesk.email.sparkpost#13]
I installed your extension yesterday, which resolved most of the issues I was having with the other one I tried. CiviMail is working correctly :-)

My problem now is that I don't seem to be able to send out transactional email from CiviCRM, such as when people subscribe to an email list or create a membership. Is there a scheduled job that needs to be created or activated that would allow these emails to send via SparkPost?

**Comment by nganivet** [comment]
No scheduled job. Make sure you git pull the latest version - some 
changes made yesterday might have corrected this error.

------ Original Message ------

**Comment by nganivet** [comment]
Closing as did not get further input.

**Comment by caniwigirl** [comment]
HI, sorry to take so long getting back to you. SparkPost suspended our account when I tried to update CiviCRM. I was only able to get everything up and going just now.

My problem seems to be with the double-opt in emails not going out when people subscribe to a mailing or join membership.

Also, do you have instructions regarding bounce processing? What type of email account do we need to process bounce and how do we set it up in 'Edit Mail Account'?
