### ISSUE TITLE
Web hook installation failing

### ISSUE THREAD

**Issue by torrance** [cividesk/com.cividesk.email.sparkpost#16]
Thanks for this extension.

We tried installing it for a client and found that the 'Send test and save' returns an error 'Cannot install webhook'.

From the documentation, it looks like the api path for webhooks has moved from /webhooks to /relay-webhooks — but if I update this in the code, I also find that the the API starts returning with errors about malformed payloads.

**Comment by torrance** [comment]
(But then I manually created the webhook and found for civimailings that *everyone* was being marked as bounced.)

**Comment by nganivet** [comment]
Please check the permissions on the API key you provided. Most probably it does not have permission to create/modify hooks. Read the documentation on necessary permissions.

**Comment by torrance** [comment]
Yes we checked that - all permissions are granted.

The response code is 301 suggesting a redirect.

**Comment by nganivet** [comment]
if you have the latest commits then copy/paste the sparkpost_log file in the exteniosn directory so I can look at it.

**Comment by torrance** [comment]
Ah thank you for the log. SparkPost was checking the callback path and was failing due to our server issuing a 301 (the server was trying to add a '/'). That's fixed.

But now I'm back to the issue where, with the web hook created, *every* recipient of a mailing is being marked as bounced. We have 2 recipients in this mailing, and only the 'davis potato bounce test <davis.potakkkk@xtra.co.nz>' user should bounce.

See below for the relevant log.

`==== ERROR in CRM_Sparkpost::call() ====
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [message] => transmission created, but with validation errors
                    [description] => message submitted for generation successfully
                    [code] => 2000
                )

        )

    [results] => stdClass Object
        (
            [rcpt_to_errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [message] => invalid data format/type
                            [description] => invalid recipient address.email: Peter Davis 
                            [code] => 1300
                        )

                )

            [total_rejected_recipients] => 1
            [total_accepted_recipients] => 1
            [id] => 102319266098992059
        )

)

Array
(
    [url] => https://api.sparkpost.com/api/v1/transmissions
    [content_type] => application/json
    [http_code] => 200
    [header_size] => 226
    [request_size] => 282
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.922098
    [namelookup_time] => 0.000137
    [connect_time] => 0.178215
    [pretransfer_time] => 0.552008
    [size_upload] => 1974
    [size_download] => 416
    [speed_download] => 451
    [speed_upload] => 2140
    [download_content_length] => 416
    [upload_content_length] => 1974
    [starttransfer_time] => 0.730148
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 54.149.113.196
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 176.9.138.87
    [local_port] => 46590
)

Array
(
    [options] => Array
        (
            [open-tracking] => 
            [click-tracking] => 
        )

    [recipients] => Array
        (
            [0] => Array
                (
                    [address] => Array
                        (
                            [email] => Peter Davis 
                        )

                )

            [1] => Array
                (
                    [address] => Array
                        (
                            [email] => peter.davis@fuzion.co.nz
                        )

                )

        )

    [metadata] => Array
        (
            [X-CiviMail-Bounce] => b.680.198711.62a50dc6f0aee7d0@prosper.org.au
        )

    [content] => Array
        (
            [email_rfc822] => MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_a44d7cce4b05b08d7fc42cbfa47728bd"
Reply-To: "Prosper Australia" <news@prosper.org.au>
Return-Path: b.680.198711.62a50dc6f0aee7d0@prosper.org.au
From: "Prosper Australia" <news@prosper.org.au>
Subject: testfz1
List-Unsubscribe: <mailto:u.680.198711.62a50dc6f0aee7d0@prosper.org.au>
job_id: 680
To: Peter Davis <peter.davis@fuzion.co.nz>
Precedence: bulk
X-CiviMail-Bounce: b.680.198711.62a50dc6f0aee7d0@prosper.org.au
Date: Thu, 07 Apr 2016 16:57:00 +1000

--=_a44d7cce4b05b08d7fc42cbfa47728bd
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=utf-8

asdsasd 

https://www.prosper.org.au/newsletters/?page=CiviCRM&q=civicrm/mailing/optout&reset=1&jid=680&qid=198711&h=62a50dc6f0aee7d0Level 1
64 Harcourt St.
North Melbourne, VIC 3051
Australia

--=_a44d7cce4b05b08d7fc42cbfa47728bd
Content-Transfer-Encoding: 8bit
Content-Type: text/html; charset=utf-8

<p>asdsasd</p>

<p>https://www.prosper.org.au/newsletters/?page=CiviCRM&amp;q=civicrm/mailing/optout&amp;reset=1&amp;jid=680&amp;qid=198711&amp;h=62a50dc6f0aee7d0<div class="location vcard"><span class="adr"><span class="street-address">Level 1</span><br /><span class="extended-address">64 Harcourt St.</span><br /><span class="locality">North Melbourne</span>, <span class="region">VIC</span> <span class="postal-code">3051</span><br /><span class="country-name">Australia</span></span></div></p>

<img src="https://www.prosper.org.au/wp-content/plugins/civicrm/civicrm/extern/open.php?q=198711" width='1' height='1' alt='' border='0'>
--=_a44d7cce4b05b08d7fc42cbfa47728bd--

        )

)



==== ERROR in CRM_Sparkpost::call() ====
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [message] => Message generation rejected
                    [description] => recipient address suppressed due to customer policy
                    [code] => 1902
                )

        )

    [results] => stdClass Object
        (
            [rcpt_to_errors] => Array
                (
                    [0] => stdClass Object
                        (
                            [message] => invalid data format/type
                            [description] => invalid recipient address.email: davis potaka bounce test 
                            [code] => 1300
                        )

                )

            [total_rejected_recipients] => 1
            [total_accepted_recipients] => 1
            [id] => 66290456455187684
        )

)

Array
(
    [url] => https://api.sparkpost.com/api/v1/transmissions
    [content_type] => application/json
    [http_code] => 400
    [header_size] => 235
    [request_size] => 282
    [filetime] => -1
    [ssl_verify_result] => 0
    [redirect_count] => 0
    [total_time] => 0.921683
    [namelookup_time] => 3.7E-5
    [connect_time] => 0.177331
    [pretransfer_time] => 0.553968
    [size_upload] => 2002
    [size_download] => 413
    [speed_download] => 448
    [speed_upload] => 2172
    [download_content_length] => 413
    [upload_content_length] => 2002
    [starttransfer_time] => 0.731311
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 54.149.113.196
    [certinfo] => Array
        (
        )

    [primary_port] => 443
    [local_ip] => 176.9.138.87
    [local_port] => 46592
)

Array
(
    [options] => Array
        (
            [open-tracking] => 
            [click-tracking] => 
        )

    [recipients] => Array
        (
            [0] => Array
                (
                    [address] => Array
                        (
                            [email] => davis potaka bounce test 
                        )

                )

            [1] => Array
                (
                    [address] => Array
                        (
                            [email] => davis.potakkkk@xtra.co.nz
                        )

                )

        )

    [metadata] => Array
        (
            [X-CiviMail-Bounce] => b.680.198712.6925db41b331247c@prosper.org.au
        )

    [content] => Array
        (
            [email_rfc822] => MIME-Version: 1.0
Content-Type: multipart/alternative;
 boundary="=_9b541e8faf053d27984a0edb2e67e713"
Reply-To: "Prosper Australia" <news@prosper.org.au>
Return-Path: b.680.198712.6925db41b331247c@prosper.org.au
From: "Prosper Australia" <news@prosper.org.au>
Subject: testfz1
List-Unsubscribe: <mailto:u.680.198712.6925db41b331247c@prosper.org.au>
job_id: 680
To: davis potaka bounce test <davis.potakkkk@xtra.co.nz>
Precedence: bulk
X-CiviMail-Bounce: b.680.198712.6925db41b331247c@prosper.org.au
Date: Thu, 07 Apr 2016 16:57:01 +1000

--=_9b541e8faf053d27984a0edb2e67e713
Content-Transfer-Encoding: 8bit
Content-Type: text/plain; charset=utf-8

asdsasd 

https://www.prosper.org.au/newsletters/?page=CiviCRM&q=civicrm/mailing/optout&reset=1&jid=680&qid=198712&h=6925db41b331247cLevel 1
64 Harcourt St.
North Melbourne, VIC 3051
Australia

--=_9b541e8faf053d27984a0edb2e67e713
Content-Transfer-Encoding: 8bit
Content-Type: text/html; charset=utf-8

<p>asdsasd</p>

<p>https://www.prosper.org.au/newsletters/?page=CiviCRM&amp;q=civicrm/mailing/optout&amp;reset=1&amp;jid=680&amp;qid=198712&amp;h=6925db41b331247c<div class="location vcard"><span class="adr"><span class="street-address">Level 1</span><br /><span class="extended-address">64 Harcourt St.</span><br /><span class="locality">North Melbourne</span>, <span class="region">VIC</span> <span class="postal-code">3051</span><br /><span class="country-name">Australia</span></span></div></p>

<img src="https://www.prosper.org.au/wp-content/plugins/civicrm/civicrm/extern/open.php?q=198712" width='1' height='1' alt='' border='0'>
--=_9b541e8faf053d27984a0edb2e67e713--

        )

)`

**Comment by torrance** [comment]
And reading closer, it looks like it's mis-parsing the name and email address - and assuming both are emails.

**Comment by torrance** [comment]
If you're willing to require php-imap, then the parse function could probably be replaced with http://php.net/manual/en/function.imap-rfc822-parse-adrlist.php

**Comment by nganivet** [comment]
I installed the regexp in a recent commit. Can you print string before, and
parsed result? I had tested regexp (see comments) but layers above have
very unpredictable formats ....

Sent from my iPhone

On Apr 7, 2016, at 1:05 AM, Torrance <notifications@github.com> wrote:

And reading closer, it looks like it's mis-parsing the name and email
address - and assuming both are emails.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/cividesk/com.cividesk.email.sparkpost/issues/16#issuecomment-206724941>

**Comment by nganivet** [comment]
torrance: can you reach me on Skype, nganivet
I have made changes today that fix the email address parsing issue, but would like to know more about the issue with creating the webhook and how you solved it so I can merge it in.

**Comment by nganivet** [comment]
Fixed with commit https://github.com/cividesk/com.cividesk.email.sparkpost/commit/0db00f37b37bdc152aae725bcb84cb9cd6ad8b55

**Comment by petednz** [comment]
hi nicholas - Torrance may not get back to you till next week sorry. not sure if anyone else here can jump in.
