### ISSUE TITLE
Emails recorded as bounced when running a stress test

### ISSUE THREAD

**Issue by madurak** [cividesk/com.cividesk.email.sparkpost#17]
Hi Nicholas,

We ran a stress test with 30K emails and found that in CiviMail reports most of these are recorded as bounced. However under sparkpost reports these are sent and the emails are also received. Can you take a look at this. I have attached some screenshots, let me know if you need any other information.

Tested in: Civi 4.6.14

<img width="536" alt="screen shot 2016-04-11 at 10 23 54" src="https://cloud.githubusercontent.com/assets/10810117/14422621/aa05542c-ffcf-11e5-96c0-1357dbab69ae.png">
<img width="1060" alt="screen shot 2016-04-11 at 10 25 14" src="https://cloud.githubusercontent.com/assets/10810117/14422632/b5210928-ffcf-11e5-8a7d-191dc99600a1.png">

-Madura

**Comment by laryn** [comment]
I see something similar with much smaller numbers of recipients. My latest micro-mailing went to 25 addresses and 23 show as bounces in CiviCRM (with bounce type of "Syntax"), although in SparkPost no bounces are reported. I am getting responses from folks who are on the "bounced" list, so I know they went through.

**Comment by nganivet** [comment]
Have you updated to the latest  version? You need to do a 'git pull' in 
the Sparkpost extension's directory. The version 1.0  released last 
weeks corrects this issue.

------ Original Message ------

**Comment by laryn** [comment]
Hmm... I thought I had the latest version but I guess I can't say for certain. I will refresh my copy and keep an eye on it when I next have to send a mailing.
Thanks!

**Comment by nganivet** [comment]
Closed as due to outdated version.

**Comment by ginkgomzd** [comment]
Hi @nganivet,
We are seeing something similar. Can you point us to the code that is supposed to address this?

**Comment by nganivet** [comment]
https://github.com/cividesk/com.cividesk.email.sparkpost/commit/9c393bd176f575aa01f98a3e8c9cb1c5dcf89534

**Comment by ginkgomzd** [comment]
based on the comment, and my limited interpretation of what that commit is doing... I think that is addressing the reverse problem? Bounces not getting logged? We are seeing bounces logged when they should not be. I suggest re-opening this issue. We will look into resolving it but won't be able to right away.

**Comment by nganivet** [comment]
What does 'We are seeing bounces logged when they should not be' mean? 
Shouldn't all bounces get logged?
Have you looked into the ConfigandLog directory for the file 
sparkpost_log? Does it contain any errors relevant to your case?

I will issue version 1.1 over the week-end with many improvements.

------ Original Message ------

**Comment by elisseck** [comment]
I had the same issue when Laryn was commenting - The issue of a large % of mailings bouncing for reason "syntax" was solved when I pulled on 4-20-16 (for civiCRM 4.6.4), if that's what you are seeing.

It might be really obvious, not sure, but we did have to actually uninstall and reinstall the extension completely rather than just pushing a new file before the issue went away for us.

**Comment by ginkgomzd** [comment]
Same thing as original poster: during a stress-test, emails marked as delayed and then delivered on SparkPost are marked bounced in CiviCRM. Will check the logs.

**Comment by ginkgomzd** [comment]
We dug deeper and came up with a feature request. See #26
