### ISSUE TITLE
CiviMail bounces, does not reach destination

### ISSUE THREAD

**Issue by cdhassell** [cividesk/com.cividesk.email.sparkpost#19]
The extension installed cleanly.  I set up a test civimail to one record, to myself.  A draft email was delivered, however when it was submitted for delivery the outgoing mail is shown as bounced in the report, and it did not reach my account.

So I have a few questions: this system has been using CiviSMTP and the outbound mail setting are still set for that.  Do I need to delete those settings?  These are on the System Settings --> Outbound Email Settings page (currently it has the SMTP server set to civismtp.uas.coop) and the CiviMail --> Mail Accounts settings page (currently with bounce processing for CiviSMTP).

Thanks!

**Comment by nganivet** [comment]
After you install the extension you have to configure it by entering 
your API key. All is explained in the documentation 
(https://github.com/cividesk/com.cividesk.email.sparkpost, scroll to the 
bottom of the page). If the extension is enabled you should no longer be 
able to access the Outbound Email Settings (it will be replaced with the 
Sparkpost settings).

------ Original Message ------

**Comment by cdhassell** [comment]
No, the API key has been entered, and the Save & Send Test Email went through.  Let me explain:  the extension did change the menu link to Outbound Mail (Sparkpost) with a link to admin/setting/sparkpost.  However on the Administration Console page, the old Outbound Email Settings still exists and points to admin/setting/smtp.  I didn't realize it wasn't supposed to be there.  My habit is to work from the console page, rather than the drop down menus.
