### ISSUE TITLE
Setting name is too generic

### ISSUE THREAD

**Issue by GinkgoFJG** [cividesk/com.cividesk.email.sparkpost#25]
As of CiviCRM 4.7, settings groups are toast. Each setting must have a unique name. This extension's `apiKey` setting name is just asking for name collisions. How about `sparkpost_apiKey` instead?

**Comment by nganivet** [comment]
Closed by 7a23a40596e36613340197dcd0141a3dcc3d572e

**Comment by GinkgoFJG** [comment]
@nganivet, I don't think this is the best fix:
* this code doesn't really belong in getSetting() -- the function is now doing a lot more than getting settings
* this code addresses a one-time need but appears in code that is part of every-day workflows
* putting this code here will make the extension harder to maintain

Let me have a stab at refactoring this into an upgrade step.

I'd reopen this ticket, but I think only repo collaborators can do that...

**Comment by nganivet** [comment]
Kinda agree: upgrade step is more 'in line with best practices' but this 
alternate method ensure that everyone is updated transparently (ie. how 
many times have you made a git pull in an extension without then going 
to the menu to check if upgrade steps was needed?).

I will accept your refactor though if you put it in an upgrade step. But 
then also include API key encryption as part of the upgrade.

More improvements coming tonight (tracking bounces on transactional 
emails), then I will release v1.1.

------ Original Message ------
