### ISSUE TITLE
Sparkpost messages in civicrm scheduled jobs log

### ISSUE THREAD

**Issue by cdhassell** [cividesk/com.cividesk.email.sparkpost#29]
The scheduled jobs log for the Sparkpost Fetch Bounces job always ends with this: "Full message: 
Finished execution of SparkPost Fetch Bounces with result: Failure, Error message: API (SparkPost, fetchbounces) does not exist (join the API team and implement it!)"   Despite this, the job does complete successfully and reports bounce data that look reasonable.  Sounds like a missing feature.  Is this normal or do I have a setting wrong somewhere?

**Comment by nganivet** [comment]
You must have used the other Sparkpost extension, this one does not have a fetch bounces job.
