### ISSUE TITLE
Using sub accounts with extension

### ISSUE THREAD

**Issue by petermcandrew** [cividesk/com.cividesk.email.sparkpost#32]
I've just come across a problem with the extension where by it gives this error message when sparkpost is configured with subaccounts:

"Domain example.com is not created and not verified in Sparkpost. Please follow instructions at https://app.sparkpost.com/account/sending-domains."

This is despite the domain being verified in sparkpost (sparkpost support also confirmed it was correctly set up)

When I created a new API key I specified that it should be linked to a specific sub account (I want to do this for reporting purposes) as we have other email systems using sparkpost, with dedicated IPs and want to keep them completely separate.  

As I suspected that this might be causing the problem I tried creating a new API key which wasn't linked to a sub account, tested it in civi and this got rid of the error message above.  

So it seems that the extension is not able to 'see' a sending domain which is shared across all subaccounts where the API key is generated and associated with a specific sub account.

It would be good to know if this last assumption is correct, and if so it might be considered as a future improvement for the extension.

Thanks
Peter

**Comment by nganivet** [comment]
Peter - All is working fine on my end with subaccounts. You need to make sure you are giving all permissions to the subaccount API key when creating the subaccount as explained in the README file. In particular it will need the Sending Domains: Read/Write permissions to verify the sending domain.

In the README I am also suggesting a one-time $40 contribution if you are using this extension. Thanks.

**Comment by nganivet** [comment]
You can change your subaccount API key permissions at https://app.sparkpost.com/account/credentials
