### ISSUE TITLE
RE: SparkPost Suppression List API Changes

### ISSUE THREAD

**Issue by laryn** [cividesk/com.cividesk.email.sparkpost#35]
Just flagging this to see if it affects this extension (via an email from SparkPost):

> I wanted to let you know that we are making a breaking change to an existing API and give you the opportunity to make necessary changes to any automated processes. Specifically, we are changing the format of the Suppression-List GET results.

> * Users who programmatically process the results of the Suppression-List API GET to update their system will be impacted by this change.
> * If you don’t use the Suppression-List API, you can disregard this message.

>In addition, we have made some significant enhancements to the Suppression-List API.

**Comment by ginkgomzd** [comment]
Thanks for posting Laryn. I was meaning to do the same. I wish they posted the notice at a URL but the email notice didn't contain one.
My first guess is that this isn't being used by the extension, but I've let my counterpart be the resident expert on the extension so my hunch is not worth much.

**Comment by GinkgoFJG** [comment]
I reviewed the code already. The extension doesn't call this API.
