### ISSUE TITLE
sparkpost notice re: suppression list API changes

### ISSUE THREAD

**Issue by lcdservices** [cividesk/com.cividesk.email.sparkpost#36]
SparkPost sent out a notice yesterday indicating changes in their suppression list API. I'm fairly certain this does not impact this extension or the integration with CiviCRM, but was curious if you've reviewed that notice to confirm. I can supply it if you did not receive it.

**Comment by GinkgoFJG** [comment]
I've reviewed the code already, and the extension doesn't use this API.

**Comment by danielstrum** [comment]
Thank you for your quick response. I love this extension! Thanks.
