### ISSUE TITLE
Webhooks Error in Civicrm 4.7.15

### ISSUE THREAD

**Issue by sofoust** [cividesk/com.cividesk.email.sparkpost#38]
After enabling the plugin and putting in the API information, which has all access granted to it, this is the error that I receive.
_SparkPost error
Could not list webhooks (Sparkpost error: Permission denied. Check that the API key is authorized for request https://api.sparkpost.com/api/v1/webhooks.)._

Let me know what information you need from me to help troubleshoot and patch the issue.

**Comment by nganivet** [comment]
sofoust - this must be an issue with your API key, please double-check that it is correct and has all permissions described in the readme.md file.

**Comment by sofoust** [comment]
The API key is given full rights, and works perfectly on everything else.
It is still having this issue when I tried other sites with different keys.
Same issue.

**Comment by nganivet** [comment]
You can put some traces in the code starting at line https://github.com/cividesk/com.cividesk.email.sparkpost/blob/master/CRM/Admin/Form/Setting/Sparkpost.php#L147 to see the exact error message that is returned by SparkPost, and then contact their support to resolve it. There is nothing we can do on our end,
