### ISSUE TITLE
Do we need a Sparkpost webhook (callback) to process bounces, etc?

### ISSUE THREAD

**Issue by tabletguy** [cividesk/com.cividesk.email.sparkpost#39]
How do you process bounces, delays, etc?

The "other" sparkpost extension for CiviCRM & Joomla recommends a webhook (callback from Sparkpost) for failures, bounces, etc.

Just switching to your extension.

**Comment by tabletguy** [comment]
I just read in issue #31 that a webhook is automatically generated and installed on the first time that the extension is configured in Joomla. Is this correct?  The documentation doesn't say anything about this, so I was going to delete the webhook.

**Comment by nganivet** [comment]
The extension automatically creates the webhook on install. You should delete the previous webhook before installing this extension as the hooks have different target URLs.

**Comment by tabletguy** [comment]
Could you please document this, and also document what the webhook title
and contents should be, so that I know I have the right one only?

**Comment by nganivet** [comment]
@tabletguy: you can delete all existing webhooks, configure the extension and test by sending the test email, then check that you have one webhook in your Sparkpost configuration. Once you have done that, feel free to write the documentation you want written and issue a PR, I will then gladly merge it.
PS. You can also show your appreciation for the work I put in this extension, and supporting you in this issue, by following instructions at the bottom of the README.md. Thanks!
