### ISSUE TITLE
Bounces not getting recorded

### ISSUE THREAD

**Issue by nc3man** [cividesk/com.cividesk.email.sparkpost#40]
We just sent out our first large mailing, about 4000 mails through Sparkpost. On the CiviCRM side, we show a very small number of bounces < 10. On the Sparkpost account, it shows on the order of about 400 bounces, of which many (>260) are hard bounces, most are "recipient doesn't exist." Why is there a difference? These emails went out over a 24 hr period in various logical batches, starting around 3pm Sat, Jan 21.

Do we just need to wait for the two to match? Also, this is a pretty new live CiviCRM instance. Most of our testing over a 3-month period was done using a test domain name. We then redirected to the final domain name about a month ago. Note that we also set SPF and DKIM for the new domain and ensured we were all green on the Sparkpost side. However, we didn't touch the CiviDesk Sparkpost configuration, etc. I'm wondering if the webhook isn't right. But if that were hosed, why would I get any bounces at all. Except they all seem to be of type "syntax" so perhaps that is not even being sent back by Sparkpost I had noticed a reply to another issue that said your webhook is setup on installation. Does that mean we need to reinstall?

Thanks for any help/advice

**Comment by nganivet** [comment]
CiviCRM classifies bounces differently than Sparkpost, and will wait for a certain number of bounces before classifying an address as 'Do Not Email'. You just have to wait over several mailings.

**Comment by nc3man** [comment]
I'm not talking about classifying as 'Do Not Email" There were 262 hard bounces of "Invalid Recipient" on the Sparkpost side. That should immediately show up as 262 bounces in CiviCRM, shouldn't it? It makes it look like all our 4,000+ emails were successfully delivered, when in fact 10% never were. Some of them are being retried and I expect a delay in recording that as a bounce in CiviCRM, but hard bounces like "Invalid Recipeint" or "Spam Block" will never get through.

**Comment by nc3man** [comment]
I know you closed this issue, but I think I know what is going wrong. On my Sparkpost account, I looked at the webhook. It was  http://sdbikecoalition.sdcbcdream.org/civicrm?page=CiviCRM&q=civicrm/sparkpost/callback.
It showed a warning and when I clicked on details, it just showed a string of 403 errors. That is expected, because we changed the domain from  http://sdbikecoalition.sdcbcdream.org/ to  https://sdbikecoalition.org/ (we also now have SSL) and blocked the IP address associated with the old domain. I created a new webhook and tested it. It was successful. So do I remove the Sparkpost old webhook that generates the 403 error? Will I be good going forward with retrieving bounces? I haven't touched anything on the CiviCRM side since the initial install (when we were  http://sdbikecoalition.sdcbcdream.org/). It was so easy and works really great. I just want to get the bounce reporting back in line. Thanks for taking a look at this.

**Comment by nganivet** [comment]
Yes, as long as the webhook is pointing to the right URL the bounces will be processed. You should delete the webhook that is pointing to the old URL.

Please show your appreciation to my work by donating per the instructions at the bottom of https://github.com/cividesk/com.cividesk.email.sparkpost. Thanks.

**Comment by nc3man** [comment]
During the last 5-6 days, we have sent about 6,500 mails with quite a few bounces on the Sparkpost side. Will those old bounces now get sent over or does Sparkpost only send them over shortly after the bounce is determined? If they don't get into CiviCRM, can I query Sparkpost for bounce details, or is that a question for the Sparkpost folks? Again, thanks for the help. We WILL donate, too ;)

**Comment by nganivet** [comment]
I do not know how Sparkpost queues/retries the bounces, but you are going to generate the same bounces on your next mailing so I would not worry too much about it. Just keep on sending and these will be recorded in the CRM on the next bounce. Thanks for your support.

**Comment by nc3man** [comment]
One more question, I had set up a shell script as follows earlier:
CIVI_ROOT="/home/karrud1/sdbikecoalition/wp-content/plugins/civicrm/civicrm"
PARAMS="-j -ssdbikecoalition.org -u USERNAME -p PASSWORD -e Job -a fetch_bounces"
nice -n19 php $CIVI_ROOT/bin/cli.php $PARAMS

I want to make sure that I should trash that shell script. I believe that was for another Sparkpost interface. If I executed that, would it create difficulties?

**Comment by nganivet** [comment]
Nothing to do with this extension, you can probably trash.

**Comment by nc3man** [comment]
Will do. That was running hourly and I had forgotten about it. It DID manage to bring in maybe a couple dozen bounces, but missed the other 400-500. Sparkpost support, btw, has helped me with obtaining the list from the last 4-5 days and suggestions for cleaning the list separately, so as to not overburden the system and also possibly cause future suppression. We'll monitor this over the next few emails. What is a typical donation you receive, if I may ask?

**Comment by nganivet** [comment]
Suggested amount on the Github page is $40 per install. I am charging my customers $20/month but they have full support including tracing their emails and resolving issues directly with Sparkpost, new features, etc. For example there have been performance improvements to this extension that my customers have, but that has not yet been merged in the public repo. Without these Sparkpost cannot send more than 3 emails/sec.

**Comment by nc3man** [comment]
Not sure I directed the payment correctly as I didn't have an Invoid ID,
but here's the receipt in case you want to make sure funds are allocated to
your extension.

Transaction Details
-----------------------
Date:        01/25/17 17:37:44
Merchant:    Cividesk
Type:        Credit Card Sale
Invoice #:
Amount:      40.00
Description:
Card Holder: Karl Rudnick
Card Number: xxxxxxxxxxxxxx5947

v8.2-ue-g-c

Thanks for a great and simple extension! For the time being, we can live
with the slow delivery on our limited budget. Emails of a couple hundred to
a couple thousand are being sent with at most about 10-12 minutes
processing time through CiviCRM (from Started to Completed).

-Karl

**Comment by nganivet** [comment]
Thank you Karl. Virginie tells me you or Mike/Erin might be at CiviCamp Denver next month, looking forward to meeting you there.

**Comment by nc3man** [comment]
Yes, all three of us will be there.
See ya then-  Karl
