### ISSUE TITLE
Batch delivery for large mailings

### ISSUE THREAD

**Issue by mfb** [cividesk/com.cividesk.email.sparkpost#48]
Can this extension do batch mail delivery to Sparkpost?   From a quick look at the code, it didn't seem like it, but I could have missed something.

Use case: I am sending a mailing to 500,000 recipients, and I'd like the whole sending and delivery process to be as fast as possible, maybe an hour or so.

The solution, if you're using SMTP, is to open up a pool of concurrent connections, sending to perhaps thousands of recipients with each connection before closing it. Or if you're using HTTPS, send as many messages as possible with each request, perhaps using a pool of parallel requests.

**Comment by nganivet** [comment]
You can use the settings screen at Administer >> CiviMail >> Mailer Settings to configure parallel and batch delivery for CiviMail. So theoretically you could achieve 500.000 per hour, though to do that you will need to talk with SparkPost first so they raise limits on your account, register a pool of dedicated IP addresses, go through a warm-up phase and have a quality mailing list as to not be flagged immediately as a spammer and be blacklisted. So possible, but will require some significant work and ongoing maintenance.

**Comment by mfb** [comment]
My question was about how this extension works at a lower level - does it make a separate HTTPS request for each mailing recipient?  If so, it might be difficult to make those requests fast enough (for this scenario, 139 per second)

**Comment by nganivet** [comment]
Per my message the CRM handles sending emails in parallel batches. SO you would not send 139 emails per seconds (the SparkPost API is not even close to accepting that kind of traffic), but you would launch 200 tasks that each send 1 email per second. You are configuring this parallel sending per the CiviCRM setup screen indicated above.

**Comment by mfb** [comment]
So it sounds like this extension doesn't do batch requests – batching, say, 139 recipients in one HTTPS request to SparkPost.

The problem with 200 mailer tasks that each send 1 or 2 emails per second is that these tasks spend a lot of time doing the TCP connection and TLS handshake, and use a lot of memory on your server while doing it.

If each TCP connection and TLS handshake could send the mailing to 100 or more recipients, then the extension would be much easier to scale up.

**Comment by nganivet** [comment]
It seems like you are not fully understanding my responses. Again, CiviCRM is doing the batching when sending emails, so it does not need to be done by this extension. The settings screen for the batching when sending emails is the one I referenced earlier. Please check the settings screen and read the CiviCRM documentation. Thanks.

**Comment by mfb** [comment]
If CiviCRM is configured to run parallel jobs, each with a large batch size, that doesn't define whether or not the mailer itself is sending them to the remote service as a batch.

While iterating through a mailing being delivered to 500,000 recipients, a mailer could create a TCP connection, make a TLS handshake, deliver the mailing to one recipient, disconnect, and move on to the next recipient.  Or it could create a TCP connection, make a TLS handshake, deliver the mailing to 200 recipients,  keep the connection alive, and move on to the next 200 recipients.  The second will be much more efficient than the first.

Let's assume I am using CiviMail to send a mailing to 500,000 recipients with a configured job size of 10,000 recipients.  I am wondering how many requests this extension will make: Will each job run make 10,000 requests, each with its own TCP connection and TLS handshake?  Or can it deliver to SparkPost more efficiently than that?

If it has to make 10,000 requests, then a feature request would be for this extension to do its own batching.  This would allow mailings to be delivered to SparkPost more quickly.

**Comment by nganivet** [comment]
OK, so what you want to know is if the extension does reuse of TCP connections. That is normally handled in the lower layers, and specifically in the curl library. You can see here for a discussion (https://github.com/cividesk/com.cividesk.email.sparkpost/pull/37), there is a small improvements when adding this, but the main limiting factor is really that you need to parallelize over multiple connections when sending email.
