### ISSUE TITLE
"Could not install webhook" error in CiviCRM 4.7.29 / Wordpress 4.9.2

### ISSUE THREAD

**Issue by nicktiberi** [cividesk/com.cividesk.email.sparkpost#55]
I have the latest code installed from master, and when I try to send a test email, I get the following error:

**SparkPost error**
Could not install webhook (Sparkpost error: HTTP return code 400, Sparkpost error code 400 (POST to webhook target URL failed with non-2xx response code 404: ). Check https://support.sparkpost.com/customer/en/portal/articles/2140916-extended-error-codes for interpretation.).

I checked Sparkpost and no webhook has been installed. Any idea why it's failing to install? My API key is correct, as above the error message it validated that my sending domain was configured properly.

I also tried creating a webhook manually at **https://mysite.com/?page=CiviCRM&q=civicrm/sparkpost/callback** which works in Sparkpost, but am still getting the same error in CiviCRM.

Thanks for any assistance!

**Comment by sunilpawar** [comment]
@nicktiberi Can you try these [changes](https://gist.github.com/sunilpawar/c9d1c83c687b07483576c42ef73a01de) 

I have Tested this on our dev environment and its working for us.

Additional Details:
PHP 7.0.30
curl : 7.40.0
Drupa: 7.59, CiviCRM: 4.7.31

**Comment by andyanderso** [comment]
@sunilpawar these changes worked great for me on 2 sites. I did find the code changes are on line 102 instead of 117. Thanks for the patch!

**Comment by nganivet** [comment]
@andyanderso Thanks for your report, we will merge this and issue a new release then.
