### ISSUE TITLE
Support for transactional emails?

### ISSUE THREAD

**Issue by JoeMurray** [cividesk/com.cividesk.email.sparkpost#6]
Does this extension support transactional emails? If so, in what way are bounces, deliveries and click-throughs on transactional emails processed, and reported to the user through the browser? FWIW, the Mandrill Transactional Email extension created a pseudo-CiviMail entry to allow recording of responses into the CiviCRM Mailing Tables and to re-use the existing mailing reports.

**Comment by nganivet** [comment]
This extensions also sends transactional emails through SparkPost. As of today it only handles bounces if there is a CiviMail mailing id, but support for transactional email bounces is planned in the     near future. Patch welcomed if you want to port the MTE code to this extension - we are also using the alterMailer hook, so should be a trivial exercise.

**Comment by nganivet** [comment]
@pradpnayak @JoeMurray - Can you please review the attached patch? Thanks.
