### ISSUE TITLE
New Release for 5.x compatibility 

### ISSUE THREAD

**Issue by kcristiano** [cividesk/com.cividesk.email.sparkpost#60]
When upgrading from 4.7 to 5.x this extension throws 500 errors when using the current released version.

Recent PRs have fixed this.  Any chance the info.xml file can be updated and a release be done?

**Comment by nganivet** [comment]
Kevin - I will issue a release shortly for another functional improvement. Can you point me to the PR fixing this 500 error so it can be included as well?

**Comment by kcristiano** [comment]
@nganivet Thanks - all the PRs are already merged in master.   Apologies for not being clear.   I do think that having a release will help orgs that rely on the built in updater as opposed to git.

**Comment by nganivet** [comment]
@kcristiano can you point me to the PR you referenced above?

**Comment by nganivet** [comment]
@kcristiano OK, I see. I will issue a new release as soon as the suppression_list branch is fully tested, so it will include the above fixes as well.

**Comment by nganivet** [comment]
@kcristiano Fixed now with the latest release.
