### ISSUE TITLE
Extension appears to not work at all on Civicrm 5.8

### ISSUE THREAD

**Issue by cdhassell** [cividesk/com.cividesk.email.sparkpost#67]
Testing on civicrm 5.8.1 shows that the extension has stopped working.  The admin menu link to Outbound Mail Settings goes to /civicrm/setting/smtp instead of /civicrm/setting/sparkpost.  The ConfigAndLog/sparkpost_log file contains many errors of the form:
```
====` ERROR in CRM_Sparkpost::call() ====
stdClass Object
(
    [errors] => Array
        (
            [0] => stdClass Object
                (
                    [message] => Forbidden.
                )

        )

)
```
This is using the latest extension version 1.3 on wordpress 4.9.9.

**Comment by nganivet** [comment]
The info.xml file indicates that this extension works with 4.7, usage with other versions is not guaranteed. I unfortunately did not gather enough donations to maintain this extension despite clearly stating on the README.md that a donation was required to support continued development and maintenance. I will be glad to provide 5.8 support if you can support this financially. Thanks.

**Comment by saparker** [comment]
I am running 5.8.1 (with Drupal 7.61 and php 7.2) and it seems to be working ok for me, but I'll keep an eye on it.
@nganivet - I sympathise with your need for funding of the maintenance. What would really help me (and perhaps others) to contribute is if you could name a total amount that the community needs to raise for you to maintain the extension for one or more years. Could it be set up as a "Make it Happen" or something? That way we could be confident that our contributions would guarantee the extension being maintained for a period. Thanks for all you've done on it.

**Comment by andyburnsco** [comment]
Echo what @saparker says. It needs to be defined more. That will result in a more fruitful fundraising campaign.
