### ISSUE TITLE
Error displayed for event registrants with an on-hold bounce email address

### ISSUE THREAD

**Issue by lkuttner** [cividesk/com.cividesk.email.sparkpost#68]
Error below is displayed on the confirmation page when a user with an on-hold bounce address submits an event registration on CiviCRM 5.4.0 using Sparkpost ext 1.3.  Registration is recorded and an email does get sent out.
Sparkpost error Sparkpost error: HTTP return code 404, Sparkpost error code (Resource could not be found: ). Check https://support.sparkpost.com/customer/en/portal/articles/2140916-extended-error-codes for interpretation.

**Comment by lkuttner** [comment]
Hi Nicholas-- we would like to make a small contribution toward helping fund continued maintenance of this extension, and encourage others who use it to do so too.  Thanks for your continued efforts.

**Comment by nganivet** [comment]
@lkuttner We estimate 2-4 hours of work to investigate, fix and release a new version of the extension. So will require a $250-$500 budget to fix this error. Is this something you can commit to? Thanks.

**Comment by lkuttner** [comment]
@nganivet Unfortunately, we are not in a financial position to put up more than the $50 contribution we just made.  Hopefully, others will come forward and contribute so you can allocate some time to updating this extension.

**Comment by jboorman** [comment]
Getting the same issue. Has any progress been made to update the extension. ..?

**Comment by nganivet** [comment]
@jboorman And ... who is going to pay for my time updating this extension? Stop being both a leech (as profiting from others work) and an annoyance to hard-working people (by posting comments such as the one above), and start thinking about what you can do to make it happen ... Cheers!

**Comment by jboorman** [comment]
We have fixed the issue ..so don't worry..
