### ISSUE TITLE
Maintenance Status

### ISSUE THREAD

**Issue by zkrebs** [cividesk/com.cividesk.email.sparkpost#71]
Is this extension still maintained? Could one reasonably implement it on 5.x CiviCRM or does it need development resources? Deciding between this, Mandrill, and CiviSMTP.

**Comment by nganivet** [comment]
Why don't you test it and report in this thread? You know, do something for the Community. Thanks.

**Comment by zkrebs** [comment]
Sure, give me a few days. There are quite a few extensions for bulk mail providers and we're looking for which one is the most actively maintained/best-bet so we can use it and sponsor it.

**Comment by laryn** [comment]
I can confirm the module is working on a 5.10.3 site.

**Comment by zkrebs** [comment]
Thanks @laryn - I am trying to set up a dev site to test this out on because there appears to be no great way to do it on a prod site without disrupting our existing mail service :D

**Comment by nganivet** [comment]
Thanks @laryn, closing issue then. I will update the README.md to indicate 5.x compatibility on the next release.
