### ISSUE TITLE
permissions renamed by SparkPost

### ISSUE THREAD

**Issue by JoeMurray** [cividesk/com.cividesk.email.sparkpost#73]
In the install instructions, it indicates the extension needs the following permissions enabled for a Sparkpost account:
* Transmissions (Read/Write)
 * Sending Domains (Read/Write)
 * Event Webhooks (Read/Write)
 * Metrics (Read-only)
 * Suppression Lists (Read/Write)

I think they may have renamed the permissions, as this is what I get when I export our permissions:

["metrics/view","message_events/view","webhooks/view","webhooks/modify","templates/view","templates/modify","templates/preview","transmissions/view","transmissions/modify","smtp/inject","recipient_lists/manage","tracking_domains/view","tracking_domains/manage","sending_domains/manage","inbound_domains/manage","suppression_lists/manage","relay_webhooks/view","relay_webhooks/modify","account/view","account/read-write","subaccount/manage","subaccount/view","ip_pools/manage","ip_pools/view","ab-testing/manage"]

**Comment by nganivet** [comment]
Nope, these are the permissions that are listed in the UI:
![image](https://user-images.githubusercontent.com/3435067/57420061-d3a65c00-71c2-11e9-9d49-7191611e2fc5.png)
