### ISSUE TITLE
SparkPost discontinuing their Messaging Events API

### ISSUE THREAD

**Issue by JoeMurray** [cividesk/com.cividesk.email.sparkpost#76]
I received an email from SparkPost today, including this:

> This is an operational notice that we are discontinuing the Message Events API on October 1, 2019. Starting on October 1, all API calls made to SparkPost must use the Events API. You are receiving this email because our data shows that the Message Events API is currently being used by your account.

They have support for migrating node.js and python but nothing for PHP. Just creating issue to find out what your plans are for dealing with this. We haven't been ecstatic about SparkPost, so would consider moving to a different service if you're not going to maintain this.

**Comment by nganivet** [comment]
Joe - I did not receive this message, and do not think this API is used in the extension as, AFAIR we're only using the sending APIs and webhooks for the return path. Oct 1st is also sufficiently far ahead that I can put this ion the 'to be dealt with later' pile. Out of curiosity, why don't you like SparkPost? We've found it very reliable and with great delivery rates. Which other service would you consider?

**Comment by JoeMurray** [comment]
Ah, one of our low-volume clients got setup with the PESC integration before yours was available and we never switched it. We'll likely do that.

They seemed good at first, but less so after a while. We've had issues with them of various types. I've provided instructions on how to configure things to overcome blacklisting problems one of our clients had https://github.com/cividesk/com.cividesk.email.sparkpost/pull/74/files. There are various other integrations.

**Comment by nganivet** [comment]
Yes, did not merge your pull request because I think this is overboard 
since CiviCRM already manages the bounces (via webhooks) and tracking. 
The only valuable setting is the backup mailer, and that was already 
explained in the help file.

------ Original Message ------

**Comment by nganivet** [comment]
Closing issue as related to another SparkPost extension, not to this one.

**Comment by ginkgomzd** [comment]
I think SparkPost is a little shady because their entry-level tier doesn't really offer much in the way of an assured sending reputation... the only reason you would use them. If you follow the practices Joe outlined, and get a dedicated IP, then I think SparkPost is no better or worse than other services.

**Comment by nganivet** [comment]
Agreed, the only way to keep a reputation is to get a dedicated IP. Any service that sends from a shared IP gets you the average reputation of all senders using the service ... very random and often not great.
