### ISSUE TITLE
Find a new maintainer?

### ISSUE THREAD

**Issue by herbdool** [cividesk/com.cividesk.email.sparkpost#95]
> As the number of voluntary donations to maintain & support the extension can still be counted with a single hand, maintenance of this extension is officially discontinued. You can still contract Cividesk, or any other CiviCRM provider, for any needed maintenance. Thanks for your understanding.

According to https://docs.civicrm.org/dev/en/latest/extensions/lifecycle/ it seems that if the extension is no longer being maintained that it should either be marked as deprecated, or be reported to https://lab.civicrm.org/extensions/extension-review-requests/issues to be delisted or unpublished.

**Comment by jaapjansma** [comment]
I would rather then handover the maintenance to a wider community. I am happy to take this on and make this a community extension as it is a useful extension.

**Comment by nganivet** [comment]
@jaapjansma Thanks for offering to maintain this extension in the future. Do you a) have clients that use this extension, and b) have a test environment in place for testing incoming PRs?

**Comment by nganivet** [comment]
@herbdool I see no reason this extension should be deprecated. Could you please suggest a language that would indicate this extension is "seeking maintainer" according to the lifecycle documents mentioned in your first post? I will then update the README.md accordingly. Thanks.

**Comment by jaapjansma** [comment]
@nganivet I have two clients who are using sparkpost. Those are long term clients and I work with them regularly. Both are in need for the transactional email bounce handling. (See #105) and one of them funded this. Both are behind CiviProxy and both use https://github.com/systopia/be.aivl.sparkpostbounceapi to track bounces through CiviProxy.

**Comment by nganivet** [comment]
@jaapjansma @herbdool @mlutfy , per this and #103 it would make sense to merge these forks into a single extension maintained on lab.civicrm. Is this something you can co-ordinate between the 3 of you?

**Comment by JoeMurray** [comment]
We would be willing to help out some as we use the extension for a few clients, though we have been migrating lately to other services in some cases.

**Comment by nganivet** [comment]
Thank you @jaapjansma, tell me if you need anything on my end.

**Comment by herbdool** [comment]
I've got too much on my plate at the moment. I'll continue to make PRs or reviewing them when I can.

**Comment by jaapjansma** [comment]
@herbdool thanks no problem.

@JoeMurray as soon as I am a (co-)maintainer I will add you. 

@nganivet I have two questions for you:
1. Can you add me to this repo as a maintainer? (with full rights)
2. Shall I move this repo to https://lab.civicrm.org?

**Comment by nganivet** [comment]
Thanks @jaapjansma 1. is Done, and I would vote yes on 2 since it is now community maintained. @mlutfy, can you please facilitate migration to lab.civicrm.org?

**Comment by jaapjansma** [comment]
Thanks!

**Comment by mlutfy** [comment]
Here is the doc for moving from Github to Gitlab:

https://lab.civicrm.org/extensions/extensions-directory/-/wikis/import-from-github (create a token, import to Gitlab, then ping me on mattermost's extension channel, or here)

**Comment by jaapjansma** [comment]
Thanks @mlutfy I have imported the project to https://lab.civicrm.org/jaapjansma/com-cividesk-email-sparkpost can you move it to https://lab.civicrm.org/extensions/com.cividesk.email.sparkpost?

**Comment by jaapjansma** [comment]
The extension is moved to https://lab.civicrm.org/extensions/sparkpost/
