### ISSUE TITLE
There have been lots of commits but no release in 3 years

### ISSUE THREAD

**Issue by herbdool** [cividesk/com.cividesk.email.sparkpost#99]
Aren't lots of people missing out on bug fixes? Please make a release so people will see that this extension is updated.

**Comment by nganivet** [comment]
Thanks @herbdool, you are correct. Would you be able to do a PR for this new release?

**Comment by seamuslee001** [comment]
If your thinking of a new release I would recommend putting something like this in it as well https://github.com/cividesk/com.cividesk.email.sparkpost/pull/103

**Comment by jaapjansma** [comment]
I have moved this extension to https://lab.civicrm.org/extensions/sparkpost/ and created a new release.
